version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  conf:
    working_directory: ~/app/
    executor: node/default
    steps:
      - aws-cli/install
      - run:
          name: Configure AWS Access Key ID
          command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run:
          name: Configure AWS Secret Access Key
          command: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run:
          name: Configure AWS default region
          command: aws configure set region $AWS_REGION
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www $S3_BUCKET_FRONTEND
  api:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Build and Compress Server
          command: |-
            npm run build
            npm run zip
      - aws-cli/install
      - eb/setup
      - run:
          name: Deploy Server
          command: |-
            eb init udagram-api --platform node.js --region $AWS_REGION
            eb use $EB_ENV
            eb setenv DB_PORT=$DB_PORT
            eb setenv JWT_SECRET=$JWT_SECRET
            eb setenv PORT=$PORT
            eb setenv POSTGRES_DB=$POSTGRES_DB
            eb setenv POSTGRES_HOST=$POSTGRES_HOST
            eb setenv POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME
            eb setenv URL=$URL
            eb deploy $EB_ENV
workflows:
  build_and_deploy:
    jobs:
      - conf: 
        filters:
          branches:
            only:
              - master
      - frontend:
        requires:
          - conf
        filters:
          branches:
            only: 
              - master
      - api:
        requires:
          - conf
        filters:
          branches:
            only: 
              - master